# This file was generated by GoReleaser. DO NOT EDIT.
cask "floop" do
  name "floop"
  desc "Behavior learning for AI agents"
  homepage "https://github.com/nvandessel/floop"
  version "0.10.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "floop"

  on_macos do
    on_intel do
      url "https://github.com/nvandessel/floop/releases/download/v#{version}/floop-#{version}-darwin-amd64.tar.gz"
      sha256 "e33696fb8e9628b4e859d9847ced459bafe7ba8b84e469c9517efc50167d2b95"
    end
    on_arm do
      url "https://github.com/nvandessel/floop/releases/download/v#{version}/floop-#{version}-darwin-arm64.tar.gz"
      sha256 "40c86186b8d9c1b1af39feb6d4ed0959ed3f0bf596b9a73ef1b44ee4b8251ab4"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/nvandessel/floop/releases/download/v#{version}/floop-#{version}-linux-amd64.tar.gz"
      sha256 "8b2a61abe9a46cef9a3c933ad6835150eabf102d343708988fb182da13762f62"
    end
    on_arm do
      url "https://github.com/nvandessel/floop/releases/download/v#{version}/floop-#{version}-linux-arm64.tar.gz"
      sha256 "fff9768c8aa6dbf1c27d9e6c6c8875497266689f7dd85aa5dbdec5179559a925"
    end
  end

  # No zap stanza required
end
