# This file was generated by GoReleaser. DO NOT EDIT.
cask "floop" do
  name "floop"
  desc "Behavior learning for AI agents"
  homepage "https://github.com/nvandessel/floop"
  version "0.12.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "floop"

  on_macos do
    on_intel do
      url "https://github.com/nvandessel/floop/releases/download/v#{version}/floop-#{version}-darwin-amd64.tar.gz"
      sha256 "52141a4d08dbb84904db03240db1f643518cb94c33e05f5fb8f941944753d8be"
    end
    on_arm do
      url "https://github.com/nvandessel/floop/releases/download/v#{version}/floop-#{version}-darwin-arm64.tar.gz"
      sha256 "ac12c211fbef45962248af0828398f372fae87a0086af34b1ac3d5feec1d2423"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/nvandessel/floop/releases/download/v#{version}/floop-#{version}-linux-amd64.tar.gz"
      sha256 "6ce2099e52a17134940b300ac1a621fce690493bc9ffdc3827d90bf1f74cd7e9"
    end
    on_arm do
      url "https://github.com/nvandessel/floop/releases/download/v#{version}/floop-#{version}-linux-arm64.tar.gz"
      sha256 "cb202ad67d21da31787b89f7bceb9c09df9b881a54ece1be27ac0615c542d2a6"
    end
  end

  # No zap stanza required
end
