# This file was generated by GoReleaser. DO NOT EDIT.
cask "frond" do
  name "frond"
  desc "Agent-first CLI for managing stacked PRs"
  homepage "https://github.com/nvandessel/frond"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "frond"

  on_macos do
    on_intel do
      url "https://github.com/nvandessel/frond/releases/download/v#{version}/frond_#{version}_darwin_amd64.tar.gz"
      sha256 "f175e30afca23a9987d08ff3e1cffc24b0586ae42a3655698702da8f81de8310"
    end
    on_arm do
      url "https://github.com/nvandessel/frond/releases/download/v#{version}/frond_#{version}_darwin_arm64.tar.gz"
      sha256 "d2fe7825e4adfdef43bfa92235045a7962341520995876e60cafb8ec8172f9e4"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/nvandessel/frond/releases/download/v#{version}/frond_#{version}_linux_amd64.tar.gz"
      sha256 "a206801ee9269982fab541cc975ab579badc0802744864575db7dc9fb5347786"
    end
    on_arm do
      url "https://github.com/nvandessel/frond/releases/download/v#{version}/frond_#{version}_linux_arm64.tar.gz"
      sha256 "6b2f42c43d977a623898ff35630e8b1b00bd76824e605b8546b97c1a3c82b829"
    end
  end

  # No zap stanza required
end
